let allRecords = [
    {
        title: "Music From Big Pink",
        artist: "The Band",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-100-The-Band-Music-From-Big-Pink.jpg?w=1000",
        year: 1968,
        genres: ["americana", "roots rock"],
        label: "Capitol",
        length: "42:22"
    },
    {
        title: "Axis: Bold as Love",
        artist: "The Jimi Hendrix Experience",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-092-Jimi-Hendrix-Experience-axis-bold-as-love.jpg?w=1000",
        year: 1967,
        genres: ["psychedelia", "pop rock"],
        label: "Track",
        length: "38:49",
    },
    {
        title: "Lemonade",
        artist: "Beyoncé",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-032-Beyonce-Lemonade.jpg?w=1000",
        year: 2016,
        genres: ["R&B", "art pop"],
        label: "Parkwood/Columbia",
        length: "45:45",
    },
    {
        title: "Pet Sounds",
        artist: "The Beach Boys",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-002-Beach-Boys-PET-SOUNDS-update.jpg?w=1000",
        year: 1966,
        genres: ["progressive pop", "chamber pop", "psychedelic pop", "art rock"],
        label: "Capitol",
        length: "35:57",
    },
    {
        title: "Horses",
        artist: "Patti Smith",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-026-Patti-Smith-HORSES.jpg?w=1000",
        year: 1975,
        genres: ["punk rock", "art punk", "garage rock"],
        label: "Arista",
        length: "43:10",
    },
    {
        title: "The Low End Theory",
        artist: "A Tribe Called Quest",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-043-A-Tribe-Called-Quest-The-Low-End-Theory.jpg?w=1000",
        year: 1991,
        genres: ["east coast hip hop", "alternative", "hip hop", "jazz rap"],
        label: "Jive",
        length: "48:03",
    },
    {
        title: "The Velvet Underground and Nico",
        artist: "The Velvet Underground",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-023-Velvet-Underground-VU_N.jpg?w=1000",
        year: 1967,
        genres: ["art rock", "experimental rock", "proto-punk", "psychedelic rock", "avant-pop"],
        label: "Verve",
        length: "47:51",
    },
    {
        title: "To Pimp a Butterfly",
        artist: "Kendrick Lamar",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-019-Kendrick-Lamar-To-Pimp-a-Butterfly.jpg?w=1000",
        year: 2015,
        genres: ["experimental hip hop", "progressive rap", "conscious hip hop", "jazz rap", "G-funk", "neo soul"],
        label: "TDE",
        length: "78:51",
    },
    {
        title: "Supa Dupa Fly",
        artist: "Missy Elliott",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-093-Missy-Misdemeanor-Elliott-Supa-Dupa-Fly.jpg?w=1000",
        year: 1997,
        genres: ["hip hop", "avant-funk", "R&B"],
        label: "The Goldmind",
        length: "60:06",
    },
    {
        title: "Purple Rain",
        artist: "Prince and the Revolution",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-008-Prince-PURPLE-RAIN.jpg?w=1000",
        year: 1984,
        genres: ["pop", "rock", "R&B", "funk-pop"],
        label: "Warner Bros.",
        length: "43:51",
    },
    {
        title: "OK Computer",
        artist: "Radiohead",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-042-Radiohead-OK-Computer.jpg?w=1000",
        year: 1997,
        genres: ["art rock", "alternative rock"],
        label: "Capitol",
        length: "53:21",
    },
    {
        title: "Blond",
        artist: "Frank Ocean",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-079-Frank-Ocean-Blonde.jpg?w=1000",
        year: 2016,
        genres: ["R&B", "avant-garde", "soul", "psychedelic pop"],
        label: "Boys Don't Cry",
        length: "60:08",
    },
    {
        title: "Darkness on the Edge of Town",
        artist: "Bruce Springsteen",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-091-bruce-springsteen-darkness-on-the-edge-of-town.jpg?w=1000",
        year: 1978,
        genres: ["hard rock", "rock", "heartland rock"],
        label: "Columbia",
        length: "42:55",
    },
    {
        title: "The Dark Side of the Moon",
        artist: "Pink Floyd",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-055-Pink-Floyd-Dark-Side-of-the-Moon.jpg?w=1000",
        year: 1973,
        genres: ["progressive rock", "psychedelia"],
        label: "EMI",
        length: "42:50",
    },
    {
        title: "The Rise and Fall of Ziggy Stardust and the Spiders From Mars",
        artist: "David Bowie",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-040-David-Bowie-The-Rise-and-Fall-of-Ziggy-Stardust.jpg?w=1000",
        year: 1972,
        genres: ["glam rock", "proto-punk"],
        label: "RCA",
        length: "38:29",
    },
    {
        title: "There’s a Riot Goin’ On",
        artist: "Sly and the Family Stone",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-082-Sly-and-the-Family-Stone-Theres-a-Riot-Goin-On.jpg?w=1000",
        year: 1971,
        genres: ["funk", "psychedelic funk", "avant-soul", "avant-pop", "deep funk"],
        label: "Epic",
        length: "47:33",
    },
    {
        title: "Enter the Wu-Tang (36 Chambers)",
        artist: "Wu-Tang Clan",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-027-Wu-Tang-Clan-ENTER-THE-WU.jpg?w=1000",
        year: 1993,
        genres: ["hardcore hip hop", "east coast hip hop", "alternative hip hop"],
        label: "Loud",
        length: "58:26",
    },
    {
        title: "What’s Going On",
        artist: "Marvin Gaye",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-001-Marvin-Gaye-WHATS-GOING-ON.jpg?w=1000",
        year: 1971,
        genres: ["progressive soul", "R&B", "symphonic pop", "psychedelic soul"],
        label: "Tamla/Motown",
        length: "35:04",
    },
    {
        title: "Random Access Memories",
        artist: "Daft Punk",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-295-Daft-Punk-Random-Access-Memories.jpg?w=1000",
        year: 2013,
        genres: ["disco", "funk", "electronic", "soft rock", "progressive pop"],
        label: "Columbia",
        length: "74:28",
    },
    {
        title: "Jagged Little Pill",
        artist: "Alanis Morissette",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-069-Alanis-Morissette-Jagged-Little-Pill.jpg?w=1000",
        year: 1995,
        genres: ["alternative rock"],
        label: "Maverick",
        length: "57:23",
    },
    {
        title: "Rubber Soul",
        artist: "The Beatles",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-035-The-Beatles-Rubber-Soul.jpg?w=1000",
        year: 1965,
        genres: ["folk rock", "rock", "pop"],
        label: "Parlophone",
        length: "34:59",
    },
    {
        title: "I Never Loved a Man the Way I Love You",
        artist: "Aretha Franklin",
        cover: "https://www.rollingstone.com/wp-content/uploads/2020/09/R1344-013-ArethaFrankNEVERLOVED-H.jpg?w=1000",
        year: 1967,
        genres: ["southern soul"],
        label: "Atlantic",
        length: "32:51",
    },
]